#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define F_CPU 16000000UL

#define SPLASH_TIME_MS 1500U
#define UI_TIMEOUT_MS 10000U
#define LOCKOUT_TIME_MS 250U
#define BEEP_TIME_MS 30U

#define TIME_MIN_MS 1U
#define TIME_MAX_MS 150U
#define MULT_MIN 1U
#define MULT_MAX 20U
#define REST_MIN_MS 0U
#define REST_MAX_MS 1000U

#define ADC_CHANNEL 0U
#define MAX_SAMPLES_PER_HALF 96U
#define DETECT_CONSECUTIVE_COUNT 3U
#define RELEASE_CONSECUTIVE_COUNT 2U
#define FEATURE_RATIO_NUM 115U
#define FEATURE_RATIO_DEN 100U
#define FEATURE_MIN_DIFF 4U
#define CENTER_ALPHA_SHIFT 5U
#define BASELINE_ALPHA_SHIFT 4U

#endif
